# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# ============================================================
# Assignment 4: Heap Data Structures - Heapsort & Priority Queue
# ============================================================

import heapq
import random
import time
import matplotlib.pyplot as plt

# ============================================================
# PART 1: HEAPSORT IMPLEMENTATION
# ============================================================

def heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and arr[left] > arr[largest]:
        largest = left

    if right < n and arr[right] > arr[largest]:
        largest = right

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)


def heap_sort(arr):
    n = len(arr)

    # Build Max Heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract Elements
    for i in range(n - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

    return arr


# ============================================================
# MERGE SORT
# ============================================================

def merge_sort(arr):
    if len(arr) > 1:

        mid = len(arr) // 2
        L = arr[:mid]
        R = arr[mid:]

        merge_sort(L)
        merge_sort(R)

        i = j = k = 0

        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                arr[k] = L[i]
                i += 1
            else:
                arr[k] = R[j]
                j += 1
            k += 1

        while i < len(L):
            arr[k] = L[i]
            i += 1
            k += 1

        while j < len(R):
            arr[k] = R[j]
            j += 1
            k += 1

    return arr


# ============================================================
# QUICK SORT
# ============================================================

def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]

    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort(left) + middle + quick_sort(right)


# ============================================================
# PERFORMANCE COMPARISON
# ============================================================

sizes = [1000, 3000, 5000, 7000, 10000]

heap_times = []
merge_times = []
quick_times = []

print("=" * 60)
print("Running Time Comparison")
print("=" * 60)

for size in sizes:

    data = random.sample(range(size * 10), size)

    # Heap Sort
    arr = data.copy()
    start = time.perf_counter()
    heap_sort(arr)
    end = time.perf_counter()
    heap_times.append(end - start)

    # Merge Sort
    arr = data.copy()
    start = time.perf_counter()
    merge_sort(arr)
    end = time.perf_counter()
    merge_times.append(end - start)

    # Quick Sort
    arr = data.copy()
    start = time.perf_counter()
    quick_sort(arr)
    end = time.perf_counter()
    quick_times.append(end - start)

    print(f"Input Size = {size}")

print("\nExecution Completed.\n")


# ============================================================
# VISUALIZATION
# ============================================================

plt.figure(figsize=(8,5))
plt.plot(sizes, heap_times, marker='o', label="Heap Sort")
plt.plot(sizes, merge_times, marker='s', label="Merge Sort")
plt.plot(sizes, quick_times, marker='^', label="Quick Sort")

plt.title("Sorting Algorithm Comparison")
plt.xlabel("Input Size")
plt.ylabel("Execution Time (seconds)")
plt.legend()
plt.grid(True)
plt.show()


# ============================================================
# PART 2: PRIORITY QUEUE IMPLEMENTATION
# ============================================================

class Task:
    def __init__(self, task_id, priority, arrival_time, deadline):
        self.task_id = task_id
        self.priority = priority
        self.arrival_time = arrival_time
        self.deadline = deadline

    def __lt__(self, other):
        # Higher priority comes first
        return self.priority > other.priority

    def __str__(self):
        return (f"Task(ID={self.task_id}, "
                f"Priority={self.priority}, "
                f"Arrival={self.arrival_time}, "
                f"Deadline={self.deadline})")


class PriorityQueue:

    def __init__(self):
        self.heap = []

    # O(log n)
    def insert(self, task):
        heapq.heappush(self.heap, task)

    # O(log n)
    def extract_max(self):
        if self.heap:
            return heapq.heappop(self.heap)
        return None

    # O(n)
    def increase_key(self, task_id, new_priority):

        for task in self.heap:
            if task.task_id == task_id:
                task.priority = new_priority
                heapq.heapify(self.heap)
                return

    # O(1)
    def is_empty(self):
        return len(self.heap) == 0

    def display(self):
        print("\nCurrent Priority Queue")
        for task in sorted(self.heap, reverse=True):
            print(task)


# ============================================================
# DEMONSTRATION
# ============================================================

pq = PriorityQueue()

pq.insert(Task(101, 3, 0, 12))
pq.insert(Task(102, 8, 1, 8))
pq.insert(Task(103, 5, 2, 15))
pq.insert(Task(104, 10, 3, 6))
pq.insert(Task(105, 7, 4, 20))

pq.display()

print("\nHighest Priority Task:")
print(pq.extract_max())

pq.display()

print("\nIncreasing Priority of Task 103 to 12...\n")

pq.increase_key(103, 12)

pq.display()

print("\nExecuting Remaining Tasks:\n")

while not pq.is_empty():
    print(pq.extract_max())

print("\nPriority Queue is Empty.")

# ============================================================
# TIME COMPLEXITY SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("TIME COMPLEXITY")
print("=" * 60)

print("Heap Sort")
print("Best Case   : O(n log n)")
print("Average Case: O(n log n)")
print("Worst Case  : O(n log n)")
print("Space       : O(1) Auxiliary")

print("\nPriority Queue Operations")
print("Insert            : O(log n)")
print("Extract Maximum   : O(log n)")
print("Increase Key      : O(n)")
print("is_empty          : O(1)")

print("\nAssignment Completed Successfully!")